spring.profiles.active=dev

#nlp.pipeline.type=iscancer
#nlp.pipeline.type=indicationapp
#nlp.pipeline.type=biomarkerapp
#nlp.pipeline.type=roa
#nlp.pipeline.type=assay
nlp.pipeline.type=specimen
#nlp.pipeline.type=her2low
#nlp.pipeline.type=pet
#nlp.pipeline.type=iscancerwho
#nlp.pipeline.type=indicationwho
#nlp.pipeline.type=isimmunology
#nlp.pipeline.type=isimmunologywho
#nlp.pipeline.type=racialdisparity
#nlp.pipeine.type=ecog
#nlp.pipeline.type=txDuration
#nlp.pipeline.type=dosage
#nlp.pipeline.type=pe
#nlp.pipeline.type=lot
#nlp.pipeline.type=asco2020
#nlp.pipeline.type=neuro
#nlp.pipeline.type=neurowho
#nlp.pipeline.type=neurosymptomswho
#nlp.pipeline.type=neurosymptoms

#Logging properties
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

files.reading.path=C:\\Users\\Sumalatha\\Xml\\Source
files.succuss.path=C:\\Users\\Sumalatha\\Xml\\Success
files.error.path=C:\\Users\\Sumalatha\\Xml\\ErrorFiles